$(function(){
    initEleEvents();	
});



function initEleEvents(){
	$("#a1").mouseover(function(){
		$("#li1").css({
			"width":"206px",
			"height":"104px",
			"left":"33px",
			"top":"7px"
		});
        $("#li2").css("left","264px");
        $("#li3").css({
			"width":"126px",
			"height":"64px",
			"left":"446px",
			"top":"48px"
		});
        $("#li4").css({
			"width":"126px",
			"height":"64px",
			"left":"596px",
			"top":"48px"
		});
        $("#li5").css({
			"width":"126px",
			"height":"64px",
			"left":"746px",
			"top":"48px"
		});
	})
    $(".contenta").mouseout(function(){
        $(".contentli").css({
        	"width":"158px",
        	"height":"80px",
        	"top":"32px"
        });
        $("#li1").css("left","23px");
        $("#li2").css("left","209px");
        $("#li3").css("left","395px");
        $("#li4").css("left","581px");
        $("#li5").css("left","767px");
    })
    $("#a2").mouseover(function(){
    	$("#li1").css("left","38px");
		$("#li2").css({
			"width":"206px",
			"height":"104px",
			"left":"219px",
			"top":"7px"
		});
        $("#li3").css("left","450px");
        $("#li4").css({
			"width":"126px",
			"height":"64px",
			"left":"632px",
			"top":"48px"
		});
        $("#li5").css({
			"width":"126px",
			"height":"64px",
			"left":"782px",
			"top":"48px"
		});
	})
    $("#a3").mouseover(function(){
    	$("#li1").css({
			"width":"126px",
			"height":"64px",
			"left":"39px",
			"top":"48px"
		});
    	$("#li2").css("left","189px");
		$("#li3").css({
			"width":"206px",
			"height":"104px",
			"left":"370px",
			"top":"7px"
		});
        $("#li4").css("left","601px");
        $("#li5").css({
			"width":"126px",
			"height":"64px",
			"left":"783px",
			"top":"48px"
		});
	})
	$("#a4").mouseover(function(){
		$("#li1").css({
			"width":"126px",
			"height":"64px",
			"left":"40px",
			"top":"48px"
		});
    	$("#li2").css({
			"width":"126px",
			"height":"64px",
			"left":"190px",
			"top":"48px"
		});
    	$("#li3").css("left","340px");
		$("#li4").css({
			"width":"206px",
			"height":"104px",
			"left":"521px",
			"top":"7px"
		});
        $("#li5").css("left","752px");
    })
    $("#a5").mouseover(function(){
    	$("#li1").css({
			"width":"126px",
			"height":"64px",
			"left":"76px",
			"top":"48px"
		});
        $("#li2").css({
			"width":"126px",
			"height":"64px",
			"left":"226px",
			"top":"48px"
		});
        $("#li3").css({
			"width":"126px",
			"height":"64px",
			"left":"376px",
			"top":"48px"
		});
        $("#li4").css("left","526px");
        $("#li5").css({
			"width":"206px",
			"height":"104px",
			"left":"707px",
			"top":"7px"
		});
	})
   
	
};
    